#!/usr/bin/python2
# -*- coding: utf-8 -*-

import sys
from hdfs.config import Config
import posixpath as psp

if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.stderr.write("hdfsls path\n")
        sys.exit(1)

    if sys.argv[1] == "-h":
        sys.stderr.write("hdfsls path\n")
        sys.exit(0)

    path = sys.argv[1]

    client = Config().get_client('dev')

    # Get all files under a given folder (arbitrary depth).
    fpaths = [psp.join(dpath, fname) 
    for dpath, _, fnames in client.walk(path)
        for fname in fnames]

    for p in fpaths:
        print p
